export const faq = [
	{
		id: 'generalEnquries',
		category:'component.generalEnquiries',
		content: [
			{
				subid:1,
				qus: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:2,
				qus: 'Duis porta ante ac dui iaculis, nec interdum ligula semper?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:3,
				qus: 'Phasellus a est id mi gravida congue?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:4,
				qus: 'Vivamus semper mi placerat, posuere ipsum sed?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			}
		]		
	},
	{
		id: 'accounts',
      category:'component.accounts',
		content: [
			{
				subid:1,
				qus: 'Mauris ac libero malesuada arcu malesuada dapibus?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:2,
				qus: 'Donec a metus eget ex suscipit finibus?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:3,
				qus: 'Donec semper mollis sem in consectetur?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:4,
				qus: 'Donec at mi vel quam finibus varius ac et lacus?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:5,
				qus: 'Donec a lacus a elit viverra aliquet?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			}
		]		
	},
	{
		id: 'features',
      category:'component.features',
		content: [
			{
				subid:1,
				qus: 'Phasellus convallis mauris sed risus convallis tempor?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:2,
				qus: 'Donec non lectus aliquam, vestibulum nisl at, tempor mauris?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:3,
				qus: 'Nullam eros magna, hendrerit non ex a, ultrices euismod ligula?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:4,
				qus: 'Maecenas non nunc convallis, euismod metus quis, facilisis lectus?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:5,
				qus: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			}
		]		
	},
	{
		id: 'rulesAndPolicies',
      category:'component.rulesAndPolicies',
		content: [
			{
				subid:1,
				qus: 'Phasellus convallis mauris sed risus convallis tempor?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:2,
				qus: 'Donec non lectus aliquam, vestibulum nisl at, tempor mauris?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:3,
				qus: 'Nullam eros magna, hendrerit non ex a, ultrices euismod ligula?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:4,
				qus: 'Maecenas non nunc convallis, euismod metus quis, facilisis lectus?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			},
			{
				subid:5,
				qus: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit?',
				ans: ' Phasellus a est id mi gravida congue. Mauris ac libero malesuada arcu malesuada dapibus. Donec a metus eget ex suscipit finibus. Donec semper mollis sem in consectetur. Cras sem tellus, semper eget imperdiet ac, imperdiet non ante. Duis nisi massa, euismod quis mattis fringilla, ullamcorper non ante. In nec sodales quam. Praesent lacinia ipsum dui, sed lacinia orci sollicitudin vel. Morbi accumsan elit sit amet dapibus tincidunt. Sed convallis nisl orci, ac gravida magna pellentesque at. Aenean quam sapien, vulputate id neque sit amet, molestie iaculis ex. Pellentesque ac lectus condimentum, auctor mauris gravida, porta velit. Curabitur gravida massa vitae turpis molestie dignissim sed sit amet nunc. Aliquam convallis odio et rutrum ornare. Sed nisl sapien, congue at lacinia dictum, commodo quis dui. Donec at mi vel quam finibus varius ac et lacus. Donec a lacus a elit viverra aliquet. Curabitur imperdiet rutrum justo vitae tincidunt. Maecenas non nisi non est porta lacinia sit amet et mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus urna neque, elementum et odio eu, placerat sollicitudin mauris. Praesent nec egestas odio. Sed sodales blandit nisi, vel convallis metus auctor ut. Sed metus arcu, convallis vel pretium vel, porta ac eros. Integer odio lacus, sollicitudin vel lorem nec, ullamcorper cursus eros. Etiam ut consectetur lorem, ut semper ex. Sed condimentum mauris justo, vel porta tortor commodo a.',
				views: '225'
			}
		]		
	}
]